### PR TITLE
Ship Akavache 5.0 Discussion

### PR DESCRIPTION
**Pull request by flagbug**
Done:
- [x] Remove support for WinRT80 #283
- [x] Update the SQLitePCL.raw reference #306 (see also #257 #264)
- [x] Resolve https://github.com/akavache/Akavache/issues/314

Next:
- [x] Retire MakeRelease.ps1 as it doesn't work anymore.
- [x] Resolve packaging story
- [ ] Verify all references to `SQLitePCLRaw.bundle_green` are removed from nuspec (Geoff missed that in the last PR)
- [x] Build Xamarin.Mac on Windows

-> THEN RELEASE.

### CODE REVIEW

**Comment by flagbug** [comment]
Replace the current implementation of `ConcurrentDictionary` with the new one from Referense Source? /cc @ghuntley

**Comment by ghuntley** [comment]
:wave: @ericsink I've read your notes am literately _right now_ trying to find a good insertion point for `SQLitePCL.Batteries.Init();`.

Current thoughts are to change the dependency to `SQLitePCLRaw.bundle_e_sqlite3` (i.e. ship sqlite.so for all platforms) vs `SQLitePCLRaw.bundle_green` (ship sqlite.so on all platforms except for iOS which uses OS version). 

@flagbug @paulcbetts guidance would be appreciated.

**Comment by ericsink** [comment]
:-)

Looking more at Akavache...

A PCL need only reference SQLitePCLRaw.core.

The bundle and the batteries Init call need to happen from the platform
code, because that's where stuff gets hooked up to the native bits.

Hope this all makes sense. I'm typing on a phone.

Using bundle e_sqlite3 makes sense to me. I personally like the consistency
of having the same SQLite lib on all platforms.

E

**Comment by ghuntley** [comment]
NuGet V3 Feed:
> https://www.myget.org/F/akavache/api/v3/index.json

NuGet V2 Feed:
> https://www.myget.org/F/akavache/api/v2

**Comment by PureWeen** [comment]
I have version "5.0.0.1476383622" from myget running on physical iOS and Android devices and haven't had any issues so far.

**Comment by flagbug** [comment]
Hm, I updated to the latest prerelease, but I'm still getting the exception `System.DllNotFoundException: /system/lib/libsqlite.so` when calling `BlobCache.Secure`. Investigating...

**Comment by Qonstrukt** [comment]
Did you manually remove the old SQLitePCL.raw_basic 0.8.6 package? Because this doesn't happen automatically when upgrading. At least not in XS.

**Comment by flagbug** [comment]
> Did you manually remove the old SQLitePCL.raw_basic 0.8.6 package? Because this doesn't happen automatically when upgrading. At least not in XS.

Aha! I still had an old version of `sqlite-net-pcl` installed. Updated it and now it works!

**Comment by flagbug** [comment]
@ghuntley The CI seems to be flaky

**Comment by kjeremy** [comment]
I see no regressions in my Android and WPF application.

**Pull request merged**
