### PR TITLE
Update the SQLite dependency to support Android 7

### PR DESCRIPTION
**Pull request by flagbug**
/cc @ghuntley @ericsink Can you review this please?

### CODE REVIEW

**Comment by ericsink** [comment]
Re:  The failure of the automatic checks:  It looks to be a problem with a missing Android API in the SDK on the build machine.  If that's related to SQLitePCL.raw, I do not yet see how.

Re:  The PR itself:  

If you have a specific preference for using the system SQLite [only] on iOS, then it looks fine.  Otherwise, I suggest using bundle_e_sqlite3 instead of bundle_green.

Did the unit tests pass for you with this change?  Just curious -- @ghuntley had a problem with that when he attempted something similar.

**Comment by flagbug** [comment]
> Re: The failure of the automatic checks: It looks to be a problem with a missing Android API in the SDK on the build machine. If that's related to SQLitePCL.raw, I do not yet see how.

@ghuntley Could you take a look at that?

>If you have a specific preference for using the system SQLite [only] on iOS, then it looks fine. Otherwise, I suggest using bundle_e_sqlite3 instead of bundle_green.

Alright, I can do that, I just had a look Azure Mobile SDK at what they are doing, and it seems like they're using `green`

> Did the unit tests pass for you with this change? Just curious -- @ghuntley had a problem with that when he attempted something similar.

Yup, they're working now, I think @ghuntley just forgot to update the dependencies of the test project, so it still used the old raw version

**Comment by ghuntley** [comment]
> If you have a specific preference for using the system SQLite [only] on iOS, then it looks fine. Otherwise, I suggest using bundle_e_sqlite3 instead of bundle_green.
> Alright, I can do that, I just had a look Azure Mobile SDK at what they are doing, and it seems like they're using green

Ugh damn; I was wanting to use `bundle_e_sqlite3` on iOS for consistency in bug reports across all platforms but looks like Azure Mobile SDK has tied our hands in this matter?

**Comment by ericsink** [comment]
I dislike the idea that all SQLitePCL.raw-using libs have to choose the same bundle.  That should not be necessary.

And if it were necessary, I would dislike it even more if bundle_green were the one everyone chose.

Use bundle_e_sqlite3.

But, to answer your question:

If two libs are using two different bundles, the last call to Batteries.Init() wins.  In the example you gave, this could mean that Akavache might end up using the iOS system SQLite, or that Azure Mobile SDK might end up using e_sqlite3, neither of which would be a tragedy.

If either "last call wins" or "first call wins" were clearly more correct, I would choose it, but this choice seems arbitrary.

**Comment by ghuntley** [comment]
Switched to bundle_e_sqlite3 and the unit tests are passing. Thank-you Eric for your on-going help.

image

**Pull request merged**
