### PR TITLE
[RFC] [WIP] Support Realm.io as storage provider

### PR DESCRIPTION
**Pull request by flagbug**
This PR adds [realm.io](http://realm.io) as alternative to the SQLite storage provider.

This is an extremely rough implementation and currently doesn't even compile, because Realm doesn't support storing `byte[]` arrays yet.

I just wanted to get this PR so people can comment on it and see the progress.

//cc @paulcbetts @shiftkey @ghuntley @AndyDentFree who might be interested in this maybe?

### CODE REVIEW

**Comment by AndyDentFree** [comment]
Consider us _extremely motivated_ by this PR and we're bumping the priority of adding the `byte[]` support.

**Comment by shiftkey** [comment]
Seems really interesting, especially on the mobile side of things.

@paulcbetts and I talked about benchmarking Akavache ages ago (I forget the specific context, there's probably a PR or two lying around), but I'd love to see how Realm stacks up against what sqlite is doing currently...

**Comment by flagbug** [comment]
@AndyDentFree :heart_eyes: :heart_eyes: :heart_eyes: 

I'm  not extremely familiar with the Realm internals, but for SQLite we're using an [OperationQueue](https://github.com/akavache/Akavache/blob/5e94aed82c6caa9e006a0232ded74d3d00bfe9f2/Akavache.Sqlite3/OperationQueue.cs) to serialize and batch the requests to SQLite, for performance reasons. Does Realm exhibit similar characteristics, or can we just throw stuff at it™ and it figures out what to do?

@shiftkey Yeah, this is something I definitely want to do! A performance test suite would also be great to have for things like https://github.com/akavache/Akavache/issues/285

**Comment by bmunkholm** [comment]
@flagbug Realm is 100% ACID. So when you do a commit it will fsync to disk twice to provide full serializable and crash safe writes.

**Comment by paulcbetts** [comment]
Very cool @flagbug

**Comment by flagbug** [comment]
@AndyDentFree Do you, by any chance, have a rough estimate when the `byte[]` support will ship?

**Comment by AndyDentFree** [comment]
There will probably be a NuGet release some time next week. We will have it updated on our master on github well before then and I'll let you know if anyone here wants to grab from source.

**Comment by flagbug** [comment]
@AndyDentFree Awesome, thanks!

**Comment by flagbug** [comment]
Rebasing this onto `akavache5-master`

@shiftkey Pls implement PR branch switching thx :crying_cat_face:

**Pull request closed without merging**
