### PR TITLE
[RFC] [WIP] Support Realm.io as storage provider

### PR DESCRIPTION
**Pull request by flagbug**
This PR supersedes #287 

This is an extremely rough implementation and currently doesn't even compile, because Realm doesn't support storing byte[] arrays yet.

I just wanted to get this PR so people can comment on it and see the progress.

### CODE REVIEW

**Comment by AndyDentFree** [comment]
Note that a PR for `byte[]` in Realm has [gone through review](https://github.com/realm/realm-dotnet/pull/567) so this is very likely to be out this week.

**Comment by AndyDentFree** [comment]
We just shipped v 0.75.0 of Realm adding `byte[]` support so please carry on with this branch.

**Comment by promontis** [comment]
@flagbug  What's the progress on this?

**Comment by flagbug** [comment]
I'l continue the work on this soonish™

**Comment by AndyDentFree** [comment]
The `ObjectForPrimaryKey` call is **significantly** more streamlined than previous queries as it avoids all the LINQ processing (after my embarrassing bug in 0.78.0 was fixed). Checking if it returns null is also the fastest check to see if an object exists.

**Pull request closed without merging**
