### PR TITLE
Remove the support for WinRT80

### PR DESCRIPTION
**Pull request by flagbug**
WinRT80 can't even be opened in VS2015 anymore

### CODE REVIEW

**Comment by shiftkey** [comment]
:thumbsup: 

Anything in particular you'd like me to look over as part of reviewing?

**Comment by flagbug** [comment]
> Anything in particular you'd like me to look over as part of reviewing?

I need some :eyes: to verify I didn't miss any remaining WinRT80 files, I always confuse WP8 and WinRT80 and WPA80 and WP80, because Microsoft Naming™

**Comment by shiftkey** [comment]
@flagbug do you think it'd be worth adding support for `win81` (which is equivalent to `netcore451`)? I guess that's the only reservation I have with removing `win8` support here...

**Comment by flagbug** [comment]
@shiftkey The [Akavache_WinRT](https://github.com/akavache/Akavache/blob/e6eb0da2da6338d54e1047fa88816859e503cd4b/Akavache/Akavache_WinRT.csproj) project should already contain support for both Windows Phone 8.1 and Windows Desktop 8.1, no?

**Comment by shiftkey** [comment]
@flagbug whoops, you're right. And the output is included in the nuspec:

```xml
<file src="bin\Release\Portable-Win81+Wpa81\Akavache.Mobile.*" target="lib\Portable-Win81+Wpa81" />
```

**Comment by flagbug** [comment]
Closing this in favor of #283 (It's the same PR, I just deleted my fork, and rebased it)

**Pull request closed without merging**
